spring:
  application:

    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manelboulares8/config-repo.git
          default-label: main
          clone-on-start: true


          # native:
            # search-locations: "classpath:/config"
          #   search-locations: file:///C:/Spring Cloud/IntelliJ_workspace/2025/manel-spring-cloud/configserver/config-repo

server:
  port: 9999