spring:
  profiles:
    active: "default"
  config :
    import : "optional:configserver:http://localhost:9999/"

  application:
    name: institut
  datasource:
    url : jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  # url: 'jdbc:h2:mem:depdb'

 # h2:
 #   console:
  #    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true

build:
  version : "1.0"

author:
  name: "manel boulares "
  email: "manel@gmail.com"